### ISSUE TITLE
quay.io/app-sre/python is now a private repo

### ISSUE THREAD

**Issue by georgettica** [openshift/cloud-ingress-operator#131]
an alternative I got is `quay.io/bitnami/python:2.7.18`
https://github.com/openshift/cloud-ingress-operator/blob/ce0b53f01aca5f4d4842865a9d630c72ab0af433/Makefile#L31

**Comment by 2uasimojo** [comment]
We should seriously _seriously_ [not be using py2](https://www.python.org/doc/sunset-python-2/).

**Comment by georgettica** [comment]
Well, say that to the pre boilerplate scripts I am finding.
Also, the jenkins slave doesn't have python3 on it

**Comment by 2uasimojo** [comment]
Nor, apparently, py2. So instead of trying to find a py2 container to replace this one, find a py3 container and port the py code to py3.

As for boilerplating cio, I think it's on @blrm/@cblecker's radar. But obvs will have to wait a month.

**Comment by georgettica** [comment]
Yeah, I tried to pull some logic out of here so I used it in rmo for now. That is why I raised the issue.
