### ISSUE TITLE
haproxy.router.openshift.io/ip_whitelist does not work when openshift is behind another reverse proxy

### ISSUE THREAD

**Issue by alfonsoalongi** [openshift/cloud-ingress-operator#153]
We have a centralized haproxy that serves request from any client to openshift and other applications outside openshift. We can't use the route annotation "haproxy.router.openshift.io/ip_whitelist" because in haproxy.template we saw that the restriction is evaluated by "tcp-request content reject" instead of "http-request deny". So can you evolve the haproxy template to evaluate the ip whitelist at HTTP layer or add another property to specify the TCP or HTTP evaluation level?

**Comment by fahlmant** [comment]
I believe https://github.com/openshift/cluster-ingress-operator is what you're looking for
