### ISSUE TITLE
Replace the Router Configuration Template

### ISSUE THREAD

**Issue by alfonsoalongi** [openshift/cloud-ingress-operator#154]
In OpenShift 3 it was possible to customize the default template configuration according the official guide at [https://docs.openshift.com/container-platform/3.11/install_config/router/customized_haproxy_router.html](https://docs.openshift.com/container-platform/3.11/install_config/router/customized_haproxy_router.html). Can you restore this feature also in OpenShift 4?

**Comment by fahlmant** [comment]
@alfonsoalongi  I believe you're looking for https://github.com/openshift/cluster-ingress-operator
